{
 "title": "Coin Flip API Dashboard",
 "description": "2024_A2_G08",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{job=\"coin-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coin API Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{name=\"coin-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Coin API CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "container_cpu_usage_seconds_total{name=\"coin-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Flips per Minute",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(flip_count{job=\"coin-api\"}[1m])*60",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Tails per Flip",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tails_count{job=\"coin-api\"} / flip_count{job=\"coin-api\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Heads per Flip",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "heads_count{job=\"coin-api\"} / flip_count{job=\"coin-api\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}